---
- hosts: localhost
  user: root
  connection: local
  gather_facts: true
  roles:
  - gen-pki

- hosts: etcd
  user: ubuntu
  become: yes
  connection: ssh
  gather_facts: true
  roles:
  - etcd

- hosts: masters
  user: ubuntu
  become: yes
  connection: ssh
  gather_facts: true
  roles:
  - master-bootstrap

- hosts: workers
  user: ubuntu
  become: yes
  connection: ssh
  gather_facts: true
  roles:
  - worker-bootstrap

- hosts: masters
  user: ubuntu
  become: yes
  connection: ssh
  gather_facts: true
  roles:
  - post
