#kubectl patch storageclass glusterfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://heketi:8080"                      ### heketi server api (service is created)
  clusterid: "ClUSTER-ID"                          ### heketi cluster id
  volumetype: "replicate:2"                   ### Number of replicas you want
