#kubectl patch storageclass glusterfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <Your storage class name>
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://heketi:8080"                      ### heketi server api (service is created)
  clusterid: "<Cluster id>"                          ### heketi cluster id
  volumetype: "replicate:<Number>"                   ### Number of replicas you want
