- name: Generate kube-proxy kubeconfig
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/root/k8s-certificates/ca.pem --embed-certs=true --server=https://{{ kube_addr }}:6443 --kubeconfig=/root/k8s-certificates/kube-proxy.kubeconfig

    kubectl config set-credentials system:kube-proxy --client-certificate=/root/k8s-certificates/proxy-csr.json.pem --client-key=/root/k8s-certificates/proxy-csr.json-key.pem --embed-certs=true --kubeconfig=/root/k8s-certificates/kube-proxy.kubeconfig

    kubectl config set-context default --cluster=kubernetes --user=system:kube-proxy --kubeconfig=/root/k8s-certificates/kube-proxy.kubeconfig

    kubectl config use-context default --kubeconfig=/root/k8s-certificates/kube-proxy.kubeconfig


- name: Generate kube-controller-manager kubeconfig
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/root/k8s-certificates/ca.pem --embed-certs=true --server=https://{{ kube_addr }}:6443 --kubeconfig=/root/k8s-certificates/kube-controller-manager.kubeconfig

    kubectl config set-credentials system:kube-controller-manager --client-certificate=/root/k8s-certificates/controller-manager-csr.json.pem --client-key=/root/k8s-certificates/controller-manager-csr.json-key.pem --embed-certs=true --kubeconfig=/root/k8s-certificates/kube-controller-manager.kubeconfig

    kubectl config set-context default --cluster=kubernetes --user=system:kube-controller-manager --kubeconfig=/root/k8s-certificates/kube-controller-manager.kubeconfig

    kubectl config use-context default --kubeconfig=/root/k8s-certificates/kube-controller-manager.kubeconfig


- name: Generate kube-scheduler kubeconfig
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/root/k8s-certificates/ca.pem --embed-certs=true --server=https://{{ kube_addr }}:6443 --kubeconfig=/root/k8s-certificates/kube-scheduler.kubeconfig

    kubectl config set-credentials system:kube-scheduler --client-certificate=/root/k8s-certificates/scheduler-csr.json.pem --client-key=/root/k8s-certificates/scheduler-csr.json-key.pem --embed-certs=true --kubeconfig=/root/k8s-certificates/kube-scheduler.kubeconfig

    kubectl config set-context default --cluster=kubernetes --user=system:kube-scheduler --kubeconfig=/root/k8s-certificates/kube-scheduler.kubeconfig

    kubectl config use-context default --kubeconfig=/root/k8s-certificates/kube-scheduler.kubeconfig


- name: Generate admin kubeconfig
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/root/k8s-certificates/ca.pem --embed-certs=true --server=https://{{ kube_addr }}:6443 --kubeconfig=/root/k8s-certificates/admin.kubeconfig

    kubectl config set-credentials admin --client-certificate=/root/k8s-certificates/admin-csr.json.pem --client-key=/root/k8s-certificates/admin-csr.json-key.pem --embed-certs=true --kubeconfig=/root/k8s-certificates/admin.kubeconfig

    kubectl config set-context default --cluster=kubernetes --user=admin --kubeconfig=/root/k8s-certificates/admin.kubeconfig

    kubectl config use-context default --kubeconfig=/root/k8s-certificates/admin.kubeconfig

- template:
    src: ../templates/bootstrap.kubeconfig
    dest: /root/k8s-certificates/bootstrap.kubeconfig
