## wordpress deployment for AMI creation
---
- hosts: all
  remote_user: ec2-user
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Install nginx
      shell: /usr/bin/amazon-linux-extras install nginx1.12 -y
    - service: name=nginx state=restarted enabled=yes
    - name: Install php-fpm-7
      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    - yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present
    - yum: name=php70-php-fpm state=latest
    - yum: name=php70-php-mysqlnd state=latest
    - yum: name=php70-php-gd state=latest
    - shell: sed -i 's/;listen.owner = nobody/listen.owner = nginx/' /etc/opt/remi/php70/php-fpm.d/www.conf && sed -i 's/;listen.group = nobody/listen.group = nginx/' /etc/opt/remi/php70/php-fpm.d/www.conf && sed -i 's/;listen.mode = 0660/listen.mode = 0660/' /etc/opt/remi/php70/php-fpm.d/www.conf
    - name: Start the php70-fpm service
      service: name=php70-php-fpm state=restarted enabled=yes
    - name: Get and install wordpress
      shell: wget http://wordpress.org/latest.tar.gz -P /home/ec2-user
    - file:
        path: /var/www/html
        state: directory
        owner: nginx
        group: nginx
    - unarchive:
        remote_src: yes
        src: /home/ec2-user/latest.tar.gz
        dest: /var/www/html
    - shell: cp -R /var/www/html/wordpress/* /var/www/html && chown -R nginx:nginx /var/www/html && rm -rf /home/ec2-user/latest.tar.gz
    - copy:
        remote_src: yes
        src: /var/www/html/wp-config-sample.php
        dest: /var/www/html/wp-config.php
        owner: nginx
        group: nginx
    - shell: sed -i "s/'database_name_here'/'"{{ db_name }}"'/" /var/www/html/wp-config.php
    - shell: sed -i "s/'username_here'/'root'/" /var/www/html/wp-config.php
    - shell: sed -i "s/'password_here'/'"{{ db_password }}"'/" /var/www/html/wp-config.php
    - shell: sed -i "s/'localhost'/'"{{ db_host }}"'/" /var/www/html/wp-config.php
    - name: Vhost creation
      template:
        src: files/basic-vhost-file
        dest: /etc/nginx/conf.d/website.conf
        owner: nginx
        group: nginx
        mode: 0644
    - template:
        src: files/wordpress.conf
        dest: /etc/nginx/wordpress.conf
        owner: nginx
        group: nginx
        mode: 0644
    - template:
        src: files/limits.conf
        dest: /etc/nginx/limits.conf
        owner: nginx
        group: nginx
        mode: 0644
    - shell: nginx -s reload
    - name: Install nrpe client and nagios plugins
      shell: amazon-linux-extras install epel -y
    - shell: yum install nagios-plugins-all nagios-plugins-nrpe nrpe -y
    - template:
        src: files/nrpe.cfg
        dest: /etc/nagios/nrpe.cfg
        owner: root
        group: root
    - template:
        src: files/check_mem.pl
        dest: /usr/lib64/nagios/plugins/check_mem.pl
        owner: root
        group: root
        mode: 0755
    - template:
        src: files/check_linux_stats.pl
        dest: /usr/lib64/nagios/plugins/check_linux_stats.pl
        owner: root
        group: root
        mode: 0755
    - template:
        src: files/perl-Sys-Statistics-Linux-0.66-14.el7.noarch.rpm
        dest: /root/perl-Sys-Statistics-Linux-0.66-14.el7.noarch.rpm
        owner: root
        group: root
        mode: 0644
    - shell: rpm -Uvh /root/perl-Sys-Statistics-Linux-0.66-14.el7.noarch.rpm
    - service: name=nrpe state=restarted enabled=yes
    - file:
        path: /tmp/downloads
        state: directory
    - name: Instal filebeat for log aggregation
      shell: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.0.0-x86_64.rpm && rpm -vi filebeat-7.0.0-x86_64.rpm
      args:
        chdir: /tmp/downloads
    - template:
        src: files/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
    - service: name=filebeat state=restarted enabled=yes
