#!/bin/bash

/usr/bin/aws s3 sync s3://"test5532412331789766-48189" /var/www/html
echo "30 * * * * root /usr/bin/aws s3 sync s3://test5532412331789766-48189 /var/www/html" > /etc/cron.d/wordpress_s3_file_sync

