variable "vpc_cidr" {}
variable "subnet_cidr" {}
variable "availability_zone" {}
variable "access_ip" {}
variable "key_name" {}
variable "public_key_path" {}
variable "instance_type" {}
variable "region" {}
variable "count" {}
